services:
  - type: web
    name: sanjeev-s6-backend-api
    env: node
    rootDir: backend
    buildCommand: npm install && npm rebuild sqlite3 --build-from-source
    startCommand: node server.js
    plan: free
